{
  imports = [
    ./audio.nix
    ./docker.nix
    ./wireshark.nix
    ./bluetooth.nix
    ./boot.nix
    ./display_manager.nix
    ./environment.nix
    ./home-manager.nix
    ./hyprland.nix
    ./locales.nix
    ./network.nix
    ./nixfeature.nix
    ./timezone.nix
    ./user.nix
    ./xserver.nix
  ];
}
